go:
    version: 1.20.4
    cgo: false
repository:
    path: github.com/pgpool/pgpool2_exporter
build:
    binaries:
      - name: pgpool2_exporter
        path: ./cmd/pgpool2_exporter
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE