FROM quay.io/prometheus/busybox:latest
LABEL maintainer="Bo Peng <pengbo@sraoss.co.jp>"

ENV POSTGRES_USERNAME postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DATABASE postgres
ENV PGPOOL_SERVICE localhost
ENV PGPOOL_SERVICE_PORT 9999
ENV PGPOOL_LISTEN_ADDRESS 9179
ENV PGPOOL_METRICS_PATH /metrics
ENV PGPOOL_LOG_LEVEL info
ENV PGPOOL_LOG_FORMAT logfmt
ENV SSLMODE disable

COPY pgpool2_exporter /bin/pgpool2_exporter

CMD ["/bin/sh", "-c", "export PGPOOL_LOG_LEVEL=\"${PGPOOL_LOG_LEVEL}\"; export PGPOOL_LOG_FORMAT=\"${PGPOOL_LOG_FORMAT}\"; export PGPOOL_METRICS_PATH=\"${PGPOOL_METRICS_PATH}\"; export PGPOOL_LISTEN_ADDRESS=\"${PGPOOL_LISTEN_ADDRESS}\"; export DATA_SOURCE_USER=\"${POSTGRES_USERNAME}\" ; export DATA_SOURCE_PASS=\"${POSTGRES_PASSWORD}\" ; export DATA_SOURCE_URI=\"${PGPOOL_SERVICE}:${PGPOOL_SERVICE_PORT}/${POSTGRES_DATABASE}?sslmode=${SSLMODE}\" ; /bin/pgpool2_exporter --web.listen-address=:${PGPOOL_LISTEN_ADDRESS} --web.telemetry-path=${PGPOOL_METRICS_PATH} --log.level=${PGPOOL_LOG_LEVEL} --log.format=${PGPOOL_LOG_FORMAT}"]

EXPOSE ${PGPOOL_LISTEN_ADDRESS}
